spring.application.name=mundial
server.port=8080

# Conexión H2 en Memoria
spring.datasource.url=jdbc:h2:mem:mundialdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Propiedades de JPA (Obligatorio 'update' para que H2 autogenere las tablas al arrancar)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# Cambia 'update' por 'create-drop' para desarrollo y pruebas limpias
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true